name: Medusa-extender Pipeline
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "npm"

      - name: 'npm install'
        run: npm install

      - name: 'run unit tests'
        run: npm run test

      - name: Push coverage badges
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: assets
            FOLDER: assets
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MESSAGE: "misc: Build new coverage badges"
